### ISSUE TITLE
"System.UnauthorizedAccessException" in mscorlib.dll in ExampleWriteDrive

### ISSUE THREAD

**Issue by Rampftl** [LordMike/RawDiskLib#10]
Hi Mike,
Another Problem. When accessing a Volume on my Computer with the "ExampleWriteDrive" it always gives me a "System.UnauthorizedAccessException" in mscorlib.dll in the line

 disk.WriteClusters(chunkData, chunk * ExampleUtilities.ClustersToRead);

even if I am acting as Administrator. Is there any trick to write to it? It is online and mounted. 

Best
Mic

**Comment by LordMike** [comment]
Windows protects certain drives a lot, to prevent this. If you have mounted the volume on the drive in question, you won't be able to write to it in this fashion.

Be very careful with that example. As it says, it _will_ destroy a formatted volume.

**Comment by LordMike** [comment]
See [this issue](https://github.com/DiscUtils/DiscUtils/issues/181#issuecomment-570067098), for more details.

**Comment by Rampftl** [comment]
Hi Mike,
thank you for the hint. It works when partition is formatted as RAW.
Best
Mic
