### ISSUE TITLE
RawDisk Resume Write

### ISSUE THREAD

**Issue by Rampftl** [LordMike/RawDiskLib#12]
Hi Mike,
I ve written a c# application which writes a partition with your RawDisk Library and it works fine. It creates a partition and writes to it. Now I want to make my program recover from a kill by restarting and continue writing to the partition. For this my program writes the last written cluster to a file.
When restarting the program, it reads the cluster number from the file, opens the existing partition with RawDisk again, seeks the offset position of the found cluster and tries to continue writing. 
But tgtDisk.WriteCluster() throws an exception "Access to the path is denied". There is no other process running accessing that partition. 
Do you have any idea, what happens? It seams that this happens, when I try to open an existing partition. 
Best
Mic

**Comment by LordMike** [comment]
This sounds like [this issue](https://github.com/DiscUtils/DiscUtils/issues/181#issuecomment-570067098).

Basically, once Windows sees your partitions, the volume manager takes over and locks the disk.

**Comment by LordMike** [comment]
You should see the same issue, if you run your program to completion, and then retry it.. 

You should get an access denied on the retry.

**Comment by Rampftl** [comment]
Many thanks for your quick answer and the very good hint. That hits the spot. I need to fool the volume manager by showing the partition as RAW as long as possible.
My solution: I start to write not from the beginning, but some clusters ahead. Then resume works perfectly. When killing the process and restart it, the write continues from the last written chunk til the end. Finally I write the first clusters, which I have stepped over. So the volume manager does not recognize the partition until it is written completely. The only non resumable part is the final writing of those first clusters. With that I can live perfectly.
Thanks again. Appreciate your Lib so much. It is a blessing.

Best
Mic
