### ISSUE TITLE
Open partition with RawDisk, which is no volume

### ISSUE THREAD

**Issue by Rampftl** [LordMike/RawDiskLib#18]
Hi LordMike,

I was wondering if RawDisk() is able to also open a partition on disk which has no volume, i.e. a partition containing a fs which is not recognized by Windows.

Best
Rampftl

**Comment by LordMike** [comment]
It definitely should. You can either access it through the partitions - windows recognizes GPT and MBR, so it should create devices for those partitions (iirc, as volumes) regardless of which FS might be present (if any).

Either that, or you can open the full drive, and then read and parse the GPT / MBR and then navigate to the correct offsets and read data there.

**Comment by Rampftl** [comment]
Thanks for your answer.

Regarding your thoughts about the partitions:

It seems that 

public RawDisk(string devicePath, FileAccess access = FileAccess.Read) 

is the right approach.

devicePath \\.\GLOBALROOT\Device\Harddisk0\Partition3 seems to be disk 0 partition 3.

Thx for your help.

**Comment by LordMike** [comment]
It does - but iirc, Partition0 is the whole disk - if that's the way you want to go.

But, you'll likely be able to use the partitions interpreted by Windows, as this can be read irrespective of the FS on the disk.

**Comment by Rampftl** [comment]
Thx, I will give it a try.
