### ISSUE TITLE
Error Creating RawDiskStream on a macbook pro running bootcamp

### ISSUE THREAD

**Issue by Lansatac** [LordMike/RawDiskLib#4]
We've been using your library in our project https://github.com/rough007/CyLR and it's been great! But we do have a user who is experiencing some issues and we were hoping you might have some insight.
Our tracking of the issue is here: https://github.com/rough007/CyLR/issues/50

The relevant part of the call stack we're getting is here:
System.ArgumentOutOfRangeException: Non-negative number required.
Parameter name: length
at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
at System.Array.Copy(Array sourceArray, Int64 sourceIndex, Array destinationArray, Int64 destinationIndex, Int64 length)
at RawDiskLib.RawDiskStream.Read(Byte[] buffer, Int32 offset, Int32 count)

I don't know if this issue is related to bootcamp or not, other users running bootcamp have been able to run the utility fine.

**Comment by Lansatac** [comment]
I should probably also mention that we're using a version of the library that is before you upgraded to .NET core.

**Comment by LordMike** [comment]
Interesting. Have you got any details on what the parameters were? Were you f.ex. supplying a 0/negative `count` value?

It doesn't seem like it's reproducible for you (it seems a user of yours encountered it?), so testing could be cumbersome. If so, it'd be fun to know what the state was at crash time, like what was the position, the length of the disk, the input values to the Read call etc.

I think my initial response here would be to add more input validation to my calls, to catch any low hanging fruit. 

As for other thoughts, it doesn't seem like an actual disk error.. Issues I've encountered in the past all related to how a disk can be read.. Typically there were bounds issues, especially around the ends of disks.

**Comment by LordMike** [comment]
As a side note, you could use the version built and available on Nuget.

**Comment by Lansatac** [comment]
I'll look into switching over to the Nuget build, that'll be a lot more convenient.
Yeah, I don't have a local repro, which makes this rather difficult to debug. I'll see if I can't find someone that can repro it in a dev environment to see if we can't get more info out of it.

**Comment by LordMike** [comment]
If you encounter other issues with the library, when switching to Nuget, please do say so. I don't think anyone has really consumed the Nuget packages since I switched to Cores build environment :).

**Comment by Lansatac** [comment]
OK, I've dug into this a bit more and here's what I've got:
We're using DiscUtils to read from the drive, (it rather serendipitously works great with RawDiskLib's RawDiskStream). This exception is happening when we're creating a new [NtfsFileSystem](https://discutils.codeplex.com/SourceControl/latest#src/Ntfs/NtfsFileSystem.cs) instance.

NtfsFileSystem calls `byte[] bytes = Utilities.ReadFully(stream, 512);` which eventually ends up [here](https://discutils.codeplex.com/SourceControl/latest#src/Utilities.cs):
```
        public static int ReadFully(IBuffer buffer, long pos, byte[] data, int offset, int length)
        {
            int totalRead = 0;
            int numRead = buffer.Read(pos, data, offset, length);
            while (numRead > 0)
            {
                totalRead += numRead;
                if (totalRead == length)
                {
                    break;
                }

                numRead = buffer.Read(pos, data, offset + totalRead, length - totalRead);
            }

            return totalRead;
        }
```
I think what's happening is that totalRead is at some point ending up greater than 512, meaning that we end up with a negative count in Read. Why that if check is an `==` and not a `>=` I couldn't really say, but I suspect that RawDisk's CreateDiskStream returns a stream that can occasionally return bad/unexpected lengths for its reads.

**Comment by Lansatac** [comment]
If you'd like we can try to add some debugging and see if @dnides can run a test for us. I've created a [branch here](https://github.com/Lansatac/RawDiskLib/tree/investigation/CyLR50), if you want to add some logging to the Read method, just push it there and I'll get it integrated with our project for testing.

**Comment by Lansatac** [comment]
Also, I pulled in the nuget libraries, and they work wonderfully. Thanks for making a great library!

**Comment by dnides** [comment]
Yes happy to help with any testing to isolate issue.

**Comment by LordMike** [comment]
Well. Truly if the `numRead` is greater than `length`, it should be handled accordingly. I've never considered that situation before :O.

I unfortunately hit decline on the invitation, but you could insert a Debug.Assert() to check the condition. If it throws, then we know that at least that part is not so trustworthy :).

**Comment by LordMike** [comment]
This code is from DiscUtils, right?

Funny coincidence. I also maintain a port of that to Dotnet Core :)
