### ISSUE TITLE
Windows 10 changes to NTFS cluster sizes

### ISSUE THREAD

**Issue by EricZimmerman** [LordMike/RawDiskLib#5]
https://dfir.ru/2019/04/23/ntfs-large-clusters/

**Comment by LordMike** [comment]
Does that even apply here?

The sectors (which RawDiskLib works with) are always 512 or 4096 bytes.

**Comment by EricZimmerman** [comment]
not sure without digging in, but wanted to pass it along. perhaps all the heavy lifting for reading NTFS is in diskutils.
