### ISSUE TITLE
Volume shadow copy access via this project? 

### ISSUE THREAD

**Issue by EricZimmerman** [LordMike/RawDiskLib#6]
I plan to start playing with this a bit more but figured I would ask if you've already done this before I out some time Into it. I would imagine it would be some derivative of the "shadow copy volume" path that would so it. 

Thank you for a great library

**Comment by LordMike** [comment]
Do you want to go through the OS, or raw?

By OS, you'll want to access the volume that ShadowCopy exposes - I'm unsure if you can view the raw disk this way, or if you're limited to a filesystem. I've never tried dumping a shadow copy to see what it actually was..

By Raw, you'll want to identify the structures on disk to find what makes up a SC, and then navigate that. I've never tried this part.

**Comment by EricZimmerman** [comment]
The os. Right now I access them via symlink but apparently raw reads against the device name works like reading a physical disk. Doing it this way would allow for getting mft send it here files not exposed when using a symlink. So I think it would work the same way as you handle physical disk now but the path format would look different.

**Comment by LordMike** [comment]
That's if the volume (which you should be able to open as a device) even has a snapshot of the MFT ... Shadow Copies are a feature in NTFS that has on disk structures to support it - how far it goes, I have no idea.

The cool way would be for the disk structures to describe segments of the disk that "was" at the time of the snapshot, and then only expose those segments/clusters when reading it - and then let a regular NTFS driver handle the rest.. 

Let me know if you find some good reversing/documentation on SC's.

**Comment by LordMike** [comment]
.. to open these with this library, a new constructor is needed. You cant't hit the Shadow Copy volumes with the current ones..

Would a preferable API be with a Disk type (e.g. Physical, Volume, ShadowCopy, ..) and then a number, or simply one taking a path handling "all the other cases".. ?

**Comment by EricZimmerman** [comment]
https://github.com/libyal/libvshadow is a project that allows for VSC access in windows and it does expose the historical MFT, $J, and so on files, so they are included in the VSCs. The Readme for that project has more info and links too.

my thought process was to leverage Windows in presenting and mapping the data out of the SC files it maintains. libvshadow does not present data back the same way Windows does and in some cases, it gives back corrupt data which wont parse (event logs, etc). This is why i was wanting to let Windows do the heavy lifting and leverage the work you have done for reading the "normalized" data off the shadow copy path. I wrote a simple program VSCMount, that can mount all VSCs via symlinks which lets you access the "normal" file system stuff just fine, but this method does not allow access to the $ files which is what i am trying to access from the VSCs. more info here:

https://binaryforay.blogspot.com/2018/09/introducing-vscmount.html?q=vscmount

The symlink method is done in an admin cmd window:

**mklink /D C:\Temp\vsc \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy1\**

where the first directory is where to present the VSC being mounted. The trailing slash is key or the command will not work right.

if things work as i have heard they work (opening up the "shadow copy volume" path), then thats all the library should need to handle, much like you are doing here:

https://github.com/LordMike/RawDiskLib/blob/master/RawDiskLib/RawDisk.cs#L53

i think adding a ShadowCopy enum  to DiskNumberType makes sense. having a method to return info on all available VSCs (the shadow copy volume and creation time being the most important) and pulling the number off the tail end of the "Shadow Copy Volume" path would make it easy. The only thing is those can change over time, or if you have other VSCs available etc, so perhaps having a means to filter by drive letter works too (similar to how /for=C: works.

Contents of shadow copy set ID: {d4b2e53f-e7c2-461e-9d0e-017e524e96a5}
   Contained 1 shadow copies at creation time: 4/30/2019 11:42:27 AM
      Shadow Copy ID: {5ddc5cfc-69b5-4a85-a554-94289008537d}
         Original Volume: (C:)\\?\Volume{dd107092-ce8f-48c4-8527-227bc4a306ff}\
         Shadow Copy Volume: \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy2

so from a simple class perspective, when VSCs are queried, getting back something like:

OriginalVolume: C:
ShadowCopyID
ShadowCopyVolume
CreationTime

would be a good start. What i havent looked at closely is whether the ShadowCopyId is static and would not change.

If you have not ever used Arsenal Recon Image mounter, it can emulate a physical disk when mounting an E01, so you can take any of the existing E01s from forensic CTFs or ones you may have (i can share some as well) and mount the E01 as a physical drive. Once it has a drive letter, vssadmin would be able to show you the VSCs for that volume.

it would be amazing if it was just that simple to extend what is happening at RawDisk.cs#L53 but with a different path format!

**Comment by LordMike** [comment]
My issue with adding such an enum is that it's not "clean", although this library will never be "not-windows". 

To enumerate shadow copies, I would look at the Windows Object tree, with [MBW.Libraries.DeviceObjectLib](https://github.com/LordMike/MBW.Libraries.DeviceObjectLib), .. to find everything.

It then provides device paths, which could be provided as strings to RawDisk. I'll look into that method.

**Comment by EricZimmerman** [comment]
sounds good. hopefully it is straight forward off that path

**Comment by LordMike** [comment]
I made a prototype RawDiskLib with a ctor for a path.

This works. It uses the DeviceObjectLib I made to get the Shadow Copies and then opens them and lists the sector count. I'm amazed it works :O.

Try it out, let me know what happens.

```csharp
            var res = NtObjects.Instance.ListDirectory(@"\Device")
                .Where(s => s.Name.StartsWith("HarddiskVolumeShadowCopy"))
                .Where(s => s.Type == WellKnownType.Device)
                .ToList();

            foreach (NtObjectBase obj in res)
            {
                Console.WriteLine(@"\\.\" + obj.Name);

                using (RawDisk rawDisk = new RawDisk(@"\\.\" + obj.Name))
                {
                    Console.WriteLine(rawDisk.SectorCount);
                }
            }
```

**Comment by EricZimmerman** [comment]
nice! i will give it a try asap.

**Comment by LordMike** [comment]
Note I've bumped RawDiskLib to 0.1.5

**Comment by EricZimmerman** [comment]
ok, will nuget see this update or should i pull from the repo?

**Comment by LordMike** [comment]
It just passed their check - check again. Possibly run a `dotnet nuget locals http-cache -c` to clear the cached 404.

**Comment by EricZimmerman** [comment]
scratch that, they just showed up! on it now

**Comment by LordMike** [comment]
I'll just quickly note that my initial runs show that it's awesomely implemented. Reading the shadow copy volume as a device and parsing it as NTFS shows a snapshot in time of data.. 

I list directories of `C:\` here, and as we can see, my new directory only shows up in the second snapshot.. With no additional work.

![image](https://user-images.githubusercontent.com/1027111/57547477-de95f380-735e-11e9-80ba-aa03cd450508.png)

**Comment by EricZimmerman** [comment]
IT WORKS!

used my existing code to copy raw mft from c:\

Name: $MFT
Size: 677380096 bytes (646 MiB)
SHA1: 3BFEABD3616E56C22D8602EA8D5FF2A79DC66DEF

used your update to to pull the MFT from a VSC:

Name: vscMFT
Size: 677380096 bytes (646 MiB)
SHA1: 26F8099447E4F2A969A67B488151E4883A0D38B2

I even applied created, modified and last accessed from the original and it worked.

BOTH MFTs parsed without error using my MFTECmd tool. when i diff them i clearly see older things!!

i cant tell you how awesome this is, and it just opened up a TON more functionality for me. I will be ripping out the symlink functionality and adding in this new method for accessing shadow copies. I will update tools and probably end up with a new one here for pulling files out of anywhere based on the path!

This should work seamlessly for E01s mounted via Arsenal Image mounter too as it would just be another device name.

This is now THE way to access VSCs on windows as its 100% seamless and gives you access to everything under the sun.

I cannot thank you enough for this. amazing work!!

![image](https://user-images.githubusercontent.com/4265254/57547812-5e0acf00-732d-11e9-8db4-2fc538f22bea.png)

**Comment by LordMike** [comment]
I'll mark this as closed.
