### ISSUE TITLE
[Bug] Unable to create `RawDisk` from numbers returned

### ISSUE THREAD

**Issue by Smurf-IV** [LordMike/RawDiskLib#8]
![image](https://user-images.githubusercontent.com/2418812/71560106-73b83a80-2a5d-11ea-80f7-2011c5876386.png)

Windows 10 x64:
All 3 fixed disks give the above exception
![image](https://user-images.githubusercontent.com/2418812/71560117-964a5380-2a5d-11ea-9bc1-4a5cd09a681e.png)

**Comment by LordMike** [comment]
I made a quick program that loops all discovered physical disks and volumes, and reads 512 bytes from them. I'm not encountering what you describe, are you perhaps not running as admin?

The code here, can throw in any case where the handle isn't good, such as missing permissions.
https://github.com/LordMike/RawDiskLib/blob/fe710e1bc549e2fa8f0706c4763004c1bfb45739/RawDiskLib/RawDisk.cs#L112-L113

![image](https://user-images.githubusercontent.com/1027111/71643594-e9b9dd00-2cbb-11ea-85bc-dc382c4bc6fc.png)

**Comment by LordMike** [comment]
Update. I've found a mismatch.

**Comment by LordMike** [comment]
So. The list from "diskpart" is not in correlation with the actual volume numbers. DiskPart has its own view on things.

The list from the RawDiskLib Utils class is correct.

**Comment by LordMike** [comment]
There is also a risk that Partition0 won't exist (it's a symlink). I haven't encountered it, but I suppose it can happen.
