### ISSUE TITLE
Bug: Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by Rampftl** [LordMike/RawDiskLib#9]
Hi, 

I am running a Windows 8.1 system with 64GB RAM, 5 Samsung SSDs

When running TestApplication and activate the Examples one after the other, the first example works but the second example returns with "Exception message: Array dimensions exceeded supported range" .  it seems to be an "System.OverflowException" in RawDiskLib.dll. Looking into Taskmanager the TestApplication consumes enormous amounts of RAM as soon as the second example is started.
This behavior is independent to which examples you run first. So you can skip the first an the second example, run the third, skip the fourth and run the fifth. In that case the fifth example runs into  the OverflowException. 
I tried building with Rider 2019.3.3 and Visual Studio 2017 Community. Tried .NET 4.0 and .NET 4.8. In all cases the problem is the same.

[Edit]: I tried to Debug with the Rider Debugger. When debugging and doing all step by step. Everything is fine. As soon as I resume the program at "example.Execute();" the memory issue happens. 

Best
Mic

**Comment by LordMike** [comment]
I found a potential issue in the listing of device objects from Win32.

**Comment by LordMike** [comment]
@Rampftl please try `0.2.0`

**Comment by Rampftl** [comment]
I tried 0.2.0. And it works! I have a feeling that everything ist going faster now. So you also did a performance optimization?
Thank you very much!

Best 
Mic
